shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - playground

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - '@rocicorp/zero-sqlite3'
  - oxc-resolver
  - simple-git-hooks
