shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - test/fixtures/vue
  - test/fixtures/nuxt

overrides:
  zero-vue: 'link:.'

allowBuilds:
  '@parcel/watcher': false
  '@rocicorp/zero-sqlite3': true
  esbuild: false
  oxc-resolver: true
  protobufjs: false
  simple-git-hooks: true
  unrs-resolver: false
